backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: home_page
    label: "Home Page"
    filter:
      field: "templateKey"
      value: "home-page"
    files:
      - file: src/pages/index.md
        label: Home
        name: index
        fields:
          - label: "Template Key"
            name: templateKey
            widget: hidden
            default: home-page
          - label: "URL Slug"
            name: slug
            widget: hidden
            default: /
          - label: SEO
            name: seo
            widget: object
            fields:
              - label: "Site Title"
                name: siteTitle
                widget: string
                default: "Site Title"
              - label: "Site Description"
                name: siteDescription
                widget: string
                required: false
                default: "Site Description"
              - label: "Site Keywords"
                name: siteKeywords
                widget: string
                required: false
                default: ""
                hint: "Comma delimited keywords"
          - label: "Header Section"
            name: headerSection
            widget: object
            fields:
              - label: "Title"
                name: title
                widget: string
              - label: "Button Visible"
                name: buttonVisible
                widget: boolean
                default: true
          - label: "Hero Section"
            name: heroSection
            widget: object
            fields:
              - label: "Title"
                name: title
                widget: string
              - label: "Description"
                name: description
                widget: markdown
                buttons: ["bold", "italic"]
          - label: "Departments Section"
            name: departmentsSection
            widget: list
            fields:
              - label: "Title"
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: "Type"
                name: type
                widget: "select"
                options:
                  [
                    "Executive Board Positions",
                    "Associate Vice President Positions",
                    "Officer Positions",
                  ]
              - label: "Positions"
                name: positions
                widget: list
                fields:
                  - label: "Position Title"
                    name: title
                    widget: string
                  - label: "Position Description"
                    name: description
                    widget: markdown
                    buttons:
                      ["bold", "italic", "bulleted-list", "numbered-list"]
  - name: apply_page
    label: "Apply Page"
    filter:
      field: "templateKey"
      value: "apply-page"
    files:
      - file: src/pages/apply.md
        label: Apply
        name: apply
        fields:
          - label: "Template Key"
            name: templateKey
            widget: hidden
            default: home-page
          - label: "URL Slug"
            name: slug
            widget: hidden
            default: /apply
          - label: SEO
            name: seo
            widget: object
            fields:
              - label: "Site Title"
                name: siteTitle
                widget: string
                default: "Site Title"
              - label: "Site Description"
                name: siteDescription
                widget: string
                required: false
                default: "Site Description"
              - label: "Site Keywords"
                name: siteKeywords
                widget: string
                required: false
                default: ""
                hint: "Comma delimited keywords"
          - label: "Header Section"
            name: headerSection
            widget: object
            fields:
              - label: "Title"
                name: title
                widget: string
              - label: "Button Visible"
                name: buttonVisible
                widget: boolean
                default: true
          - label: "Hero Section"
            name: heroSection
            widget: object
            fields:
              - label: "Title"
                name: title
                widget: string
              - label: "Description"
                name: description
                widget: markdown
                buttons: ["bold", "italic"]
          - label: "Aritable Embed Link"
            name: link
            widget: string
